model_list:
  - model_name: Qwen/Qwen3-235B-A22B-Instruct-2507
    litellm_params:
      model: openai/Qwen/Qwen3-235B-A22B-Instruct-2507
      api_base: os.environ/MODEL_SCOPE_BASE_URL
      api_key: os.environ/MODEL_SCOPE_API_KEY
      timeout: 120
  - model_name: gpt-5.5
    litellm_params:
      model: openai/gpt-5.5
      api_base: os.environ/OWIWO_BASE_URL
      api_key: os.environ/OWIWO_API_KEY
      headers:
        User-Agent: Mozilla/5.0
      timeout: 120

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  request_timeout: 120
  set_verbose: false
